version: '3'

services:
  front:
    build: ./docker/front
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/usr/src/app
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "4321:4321"
    restart: always
    volumes:
      - ./api/src:/usr/src/app/api/src
      - ./api/database.sqlite:/usr/src/app/api/database.sqlite
    # env_file:
    #   - ./api/.env

  redis:
    image: redis:alpine
    restart: always

volumes:
  node_modules: