export default {
  "transactions": [
    {
      "receipt": false,
      "emitterName": "Restaurante Pepe",
      "description": "Comida de año nuevo",
      "amount": 35,
      "currency": "EUR",
      "transactionDate": "2020-01-01",
      "valueDate": "2021-01-01",
      "balance": 500,
    },
    {
      "receipt": false,
      "emitterName": "Restaurante Ocho Treses",
      "description": "Cena de Navidad en el curro",
      "amount": 30,
      "currency": "EUR",
      "transactionDate": "2020-12-18",
      "valueDate": "2020-12-18",
      "balance": 650,
    },
    {
      "receipt": false,
      "emitterName": "Pepe Fernández",
      "description": "pago 1",
      "amount": 5,
      "currency": "EUR",
      "transactionDate": "2020-01-24",
      "valueDate": "2020-01-24",
      "balance": 788,
    },
    {
      "receipt": false,
      "emitterName": "Pepe Fernández",
      "description": "pago 2",
      "comments": "me debía el regalo para Juanito",
      "amount": 6,
      "currency": "EUR",
      "transactionDate": "2020-01-24",
      "valueDate": "2020-01-24",
      "balance": 930,
    },
    {
      "receipt": false,
      "receiverName": "Movistar",
      "description": "pago",
      "amount": -60,
      "currency": "EUR",
      "transactionDate": "2020-01-24",
      "valueDate": "2020-01-24",
      "balance": 1222.30,
    },
    {
      "receipt": false,
      "emitterName": "Oscar",
      "description": "segunda transacción de prueba",
      "amount": 10,
      "currency": "EUR",
      "transactionDate": "2020-01-23",
      "valueDate": "2020-01-23",
      "balance": 1230.30,
    }
  ],
  "balance": 1200
}