const actions = [
  // user
  'USER_RESET_STATE',
  // transactions
  'TRANSACTIONS_CONTEXT_MENU_CHANGE_INDEX',
  'TRANSACTIONS_CONTEXT_MENU_CHANGE_ID',
  'TRANSACTIONS_CONTEXT_MENU_CHANGE_POSITION',
  'TRANSACTIONS_CREATE_EDIT_DIALOG_OPEN',
  'TRANSACTIONS_CREATE_EDIT_DIALOG_CLOSE',
  'TRANSACTIONS_TOGGLE_CHECKBOX',
  'TRANSACTIONS_DETAILS_DIALOG_OPEN',
  'TRANSACTIONS_DETAILS_DIALOG_CLOSE',
  'TRANSACTIONS_TOGGLE_CHARTS',
];

const actionTypes = {};
actions.forEach((action) => {
  actionTypes[action] = action;
});

export default actionTypes;
